name: "My bastard"
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["bastardkb_left","bastardkb_right"]'
      kconfig: '["CONFIG_ZMK_PM_SOFT_OFF=y\nCONFIG_ZMK_SLEEP=y\nCONFIG_ZMK_MOUSE=y"]'
      branches: '["gogamid/zmk/main"]'
