name: "My Build"
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left","corne_right"]'
      branches: '["caksoylar/zmk/feat/mouse-keys-3.2"]'
